### ISSUE TITLE
Define for disabling html5 deltaMode workaround in Scroller.hx

### ISSUE THREAD

**Issue by nadako** [feathersui/feathersui-openfl#122]
We're considering integrating FeathersUI in our codebase and so far it works like a charm except one small thing I've noticed: In `Scroller.hx` there's a hack/workaround to properly handle mouse wheel delta modes which actually breaks wheel scrolling for us, because we use our own OpenFL fork that has this fixed on the lower level, so actual Flash API users don't have to care about it.

Would it be possible to fence the workaround in Feathers with an #if so it can be disabled for specific build configurations like ours?

**Comment by joshtynjala** [comment]
> we use our own OpenFL fork that has this fixed on the lower level

Is this a fix that we could upstream from your fork? As you mentioned, this is a workaround for a bug. If we can fix the bug, then the workaround won't be needed.

**Comment by nadako** [comment]
I don't know how applicable is it (since our fork is from a very old version) or even whether it's fully correct (since it was "good enough" for us), but it's here if someone wants to take a look: https://github.com/innogames/openfl/blob/61cf4c14d980e31c19988f93b104f43b5681759b/src/lime/_backend/html5/HTML5Window.hx#L379

**Comment by joshtynjala** [comment]
Thanks. I don't particularly care if it's "fully correct" either because "more correct than what we have now" should still be a good improvement.

I see your forked version is 7.1.1. After I fix the OpenFL issue, I was hoping to keep the workaround in Feathers UI with something like `#if (openfl < 9.x.x)`. However, that still won't work for your fork. I guess I'll need to create a new flag for it after all.

**Comment by joshtynjala** [comment]
I added support for `-Dfeathersui_innogames_openfl`, which is meant to cover this and any other divergences we discover between innogames/openfl and openfl/openfl. It will be included in the upcoming Feathers UI 1.1.
