### ISSUE TITLE
ValidatingSprite using map instead of flags

### ISSUE THREAD

**Issue by nevergarden** [feathersui/feathersui-openfl#159]
In `ValidatingSprite` class you have used `Map` to check validations, is there any reason you didn't use flags?
Like in starling feathers you used string to keep consistency with existing code.

https://github.com/feathersui/feathersui-openfl/blob/697f007ce0a9dee484274a2ed4716926a43c3cd8/src/feathers/core/ValidatingSprite.hx#L106

This is a proposal to make validation better:

since you used enum as invalidation flag making it abstract giving them binary values:
```haxe
abstract enum InvalidationFlag(Int) from Int {
	var STATE = 1;
	var SIZE  = 2;
	var STYLE = 4;
	var SKIN  = 8;
	var LAYOUT = 16;
	var DATA = 32;
	var SCROLL = 64;
	var SELECTION = 128;
	var FOCUS = 256;
	var SORT = 512;
}
```
and use functions to set and unset flags:
```haxe
...
	var SORT = 512;
	
	public inline function set(flag:InvalidationFlag):Void {
		this |= cast(flag,Int);
	}

	public inline function unset(flag:InvalidationFlag):Void {
		this &= ~cast(flag,Int);
	}
}
```

now if you have `_invalidationFlags:InvalidationFlag = 0` in `ValidatingSprite`
You just have to `_invalidationFlags.set(STATE)` to set state as invalidation flag.

The thing is when you want to check if it has invalidation you can do it with `==` operator.
```haxe
if(_invalidationFlags != 0) { // is invalid 
```

**Comment by joshtynjala** [comment]
The Starling version uses AS3's `Object` as a primitive map, and a class with static constants as a primitive enum. I probably didn't see any reason to improve much beyond that, since it worked pretty well in my experience.

It's been a long time, but it seems likely that when I first starting porting to Haxe that I would have used an anonymous structure in Haxe the same way I used an AS3 `Object`, but obviously, I'd need to access flags using `Reflect.field()` and `Reflect.setField()`, which is a little more verbose.  I probably quickly converted that to a `Map<String, Bool>` for cleaner code. Then, `Map<InvalidationFlag, Bool>` with `enum InvalidationFlag` is just a step further to improve on using string values.

It was a while until I was comfortable with abstracts or abstract enums, so something like what you propose never would have crossed my mind at the time (validation would have been the first thing that I ported). I tend to avoid abstracts, unless I feel like it can make a public API more convenient by doing some automatic type conversion (like the abstracts I created for `DisplayObjectFactory`/`DisplayObjectRecycler` that make it easy to pass in a `Class` or function). I've yet to find a solid use-case for enum abstracts in the style of code that I write.

I'm also not really a fan of bit flags. It always feels hacky to me, or like premature optimization.

I'm generally happy with how the invalidation flags work, so the internal implementation is unlikely to change, unless a compelling reason can be proposed for why something else is significantly better.

**Comment by nevergarden** [comment]
The way using a flag as a single `Int` (`enum abstract` is only for syntax sugar) is to get rid of:
https://github.com/feathersui/feathersui-openfl/blob/697f007ce0a9dee484274a2ed4716926a43c3cd8/src/feathers/core/ValidatingSprite.hx#L297C3-L297C54

for loop to check if something is invalid or not.
```haxe
if(flag != 0) {
// is invalid
}
```

**Comment by joshtynjala** [comment]
I'm still happy with the design, but thanks for encouraging me to take a second look. I actually ended up finding a bug, and there were a couple of places where I could simplify the code a bit.
